#!/usr/bin/env bash
# Pull stream keys from Azure Key Vault into destinations.env for the relay.
set -euo pipefail

ENV_FILE="/opt/multistream/etc/destinations.env"
CONFIG_ENV="/opt/multistream/etc/multistream.env"

if [[ ! -f "$CONFIG_ENV" ]]; then
  echo "missing $CONFIG_ENV" >&2
  exit 1
fi

# shellcheck disable=SC1090
source "$CONFIG_ENV"

: "${KEY_VAULT_NAME:?KEY_VAULT_NAME required}"

# Talk to Key Vault over REST with the VM's managed identity. The Azure CLI
# needs `az login --identity` plus ~1s of interpreter startup per secret,
# which dominated the time to prepare a live.
KV_TOKEN="$(curl -sS -H Metadata:true --max-time 10 \
  "http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fvault.azure.net" \
  | python3 -c 'import json,sys; print(json.load(sys.stdin).get("access_token",""))' 2>/dev/null || true)"

if [[ -z "$KV_TOKEN" ]]; then
  echo "IMDS token unavailable; falling back to az CLI" >&2
  az login --identity --output none 2>/dev/null || az login --identity --output none
fi

get_secret_optional() {
  local name="$1"
  if [[ -n "$KV_TOKEN" ]]; then
    curl -sS --max-time 15 -H "Authorization: Bearer ${KV_TOKEN}" \
      "https://${KEY_VAULT_NAME}.vault.azure.net/secrets/${name}?api-version=7.4" \
      | python3 -c 'import json,sys
try:
    print(json.load(sys.stdin).get("value",""))
except Exception:
    print("")' 2>/dev/null || true
  else
    az keyvault secret show --vault-name "$KEY_VAULT_NAME" --name "$name" \
      --query value -o tsv 2>/dev/null || true
  fi
}

get_secret() {
  local name="$1" value
  value="$(get_secret_optional "$name")"
  if [[ -z "$value" ]]; then
    echo "required secret '$name' is missing from $KEY_VAULT_NAME" >&2
    exit 1
  fi
  printf '%s' "$value"
}

# Single-quote a value so destinations.env survives `source` even when the
# value contains &, ?, spaces or other shell metacharacters. Facebook's
# API-issued stream keys carry a query string, and an unquoted & would be
# parsed as a background-job separator and silently drop the assignment.
shell_quote() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

YT_KEY="$(get_secret youtube-stream-key)"
FB_KEY="$(get_secret facebook-stream-key)"
INGEST_KEY="$(get_secret ingest-stream-key)"

# YouTube primary ingest
YT_URL="rtmp://a.rtmp.youtube.com/live2/${YT_KEY}"

# Facebook: prefer the exact secure_stream_url the Live Video API handed us,
# because the API binds the key to a specific ingest host.
FB_URL="$(get_secret_optional facebook-stream-url)"
if [[ -z "$FB_URL" ]]; then
  # No stored URL (key pasted by hand, or set before we started saving it).
  FB_URL="rtmps://live-api-s.facebook.com:443/rtmp/${FB_KEY}"
fi

umask 077
{
  echo "# Generated by sync-secrets.sh — do not edit by hand"
  echo "YOUTUBE_STREAM_KEY=$(shell_quote "$YT_KEY")"
  echo "FACEBOOK_STREAM_KEY=$(shell_quote "$FB_KEY")"
  echo "INGEST_STREAM_KEY=$(shell_quote "$INGEST_KEY")"
  echo "YOUTUBE_RTMP_URL=$(shell_quote "$YT_URL")"
  echo "FACEBOOK_RTMP_URL=$(shell_quote "$FB_URL")"
} > "$ENV_FILE"

echo "synced secrets to $ENV_FILE"
