#!/usr/bin/env bash
# Pull stream keys from Azure Key Vault into destinations.env for the relay.
set -euo pipefail

ENV_FILE="/opt/multistream/etc/destinations.env"
CONFIG_ENV="/opt/multistream/etc/multistream.env"

if [[ ! -f "$CONFIG_ENV" ]]; then
  echo "missing $CONFIG_ENV" >&2
  exit 1
fi

# shellcheck disable=SC1090
source "$CONFIG_ENV"

: "${KEY_VAULT_NAME:?KEY_VAULT_NAME required}"

# Managed identity (VM system-assigned)
az login --identity --output none 2>/dev/null || az login --identity --output none

get_secret() {
  local name="$1"
  az keyvault secret show --vault-name "$KEY_VAULT_NAME" --name "$name" --query value -o tsv
}

get_secret_optional() {
  local name="$1"
  az keyvault secret show --vault-name "$KEY_VAULT_NAME" --name "$name" --query value -o tsv 2>/dev/null || true
}

# Single-quote a value so destinations.env survives `source` even when the
# value contains &, ?, spaces or other shell metacharacters. Facebook's
# API-issued stream keys carry a query string, and an unquoted & would be
# parsed as a background-job separator and silently drop the assignment.
shell_quote() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

YT_KEY="$(get_secret youtube-stream-key)"
FB_KEY="$(get_secret facebook-stream-key)"
INGEST_KEY="$(get_secret ingest-stream-key)"

# YouTube primary ingest
YT_URL="rtmp://a.rtmp.youtube.com/live2/${YT_KEY}"

# Facebook: prefer the exact secure_stream_url the Live Video API handed us,
# because the API binds the key to a specific ingest host.
FB_URL="$(get_secret_optional facebook-stream-url)"
if [[ -z "$FB_URL" ]]; then
  if [[ "$FB_KEY" == *\?* ]]; then
    # API-issued key (has a query string) — belongs to the api ingest host.
    FB_URL="rtmps://rtmp-api.facebook.com:443/rtmp/${FB_KEY}"
  else
    # Key pasted by hand from Facebook Live Producer.
    FB_URL="rtmps://live-api-s.facebook.com:443/rtmp/${FB_KEY}"
  fi
fi

umask 077
{
  echo "# Generated by sync-secrets.sh — do not edit by hand"
  echo "YOUTUBE_STREAM_KEY=$(shell_quote "$YT_KEY")"
  echo "FACEBOOK_STREAM_KEY=$(shell_quote "$FB_KEY")"
  echo "INGEST_STREAM_KEY=$(shell_quote "$INGEST_KEY")"
  echo "YOUTUBE_RTMP_URL=$(shell_quote "$YT_URL")"
  echo "FACEBOOK_RTMP_URL=$(shell_quote "$FB_URL")"
} > "$ENV_FILE"

echo "synced secrets to $ENV_FILE"
