#!/usr/bin/env bash
# Pull stream keys from Azure Key Vault into destinations.env for the relay.
set -euo pipefail

ENV_FILE="/opt/multistream/etc/destinations.env"
CONFIG_ENV="/opt/multistream/etc/multistream.env"

if [[ ! -f "$CONFIG_ENV" ]]; then
  echo "missing $CONFIG_ENV" >&2
  exit 1
fi

# shellcheck disable=SC1090
source "$CONFIG_ENV"

: "${KEY_VAULT_NAME:?KEY_VAULT_NAME required}"

# Managed identity (VM system-assigned)
az login --identity --output none 2>/dev/null || az login --identity --output none

get_secret() {
  local name="$1"
  az keyvault secret show --vault-name "$KEY_VAULT_NAME" --name "$name" --query value -o tsv
}

YT_KEY="$(get_secret youtube-stream-key)"
FB_KEY="$(get_secret facebook-stream-key)"
INGEST_KEY="$(get_secret ingest-stream-key)"

# YouTube primary ingest
YT_URL="rtmp://a.rtmp.youtube.com/live2/${YT_KEY}"
# Facebook Live — RTMPS on 443
FB_URL="rtmps://live-api-s.facebook.com:443/rtmp/${FB_KEY}"

umask 077
cat > "$ENV_FILE" <<EOF
# Generated by sync-secrets.sh — do not edit by hand
YOUTUBE_STREAM_KEY=${YT_KEY}
FACEBOOK_STREAM_KEY=${FB_KEY}
INGEST_STREAM_KEY=${INGEST_KEY}
YOUTUBE_RTMP_URL=${YT_URL}
FACEBOOK_RTMP_URL=${FB_URL}
EOF

echo "synced secrets to $ENV_FILE"
