[sshd]
enabled = true
maxretry = 5
findtime = 15m
bantime = 1h

[nginx-limit-req]
enabled = true
filter = nginx-limit-req
logpath = /var/log/nginx/error.log
maxretry = 10
findtime = 10m
bantime = 1h

[multistream-ui]
enabled = true
filter = multistream-ui
port = http,https
logpath = /var/log/nginx/access.log
backend = auto
maxretry = 8
findtime = 15m
bantime = 1h
